Recommended install location in README.md
bsmn/bsmn-pipeline pull request #18
Opened 2019-01-16 17:44 UTC by attilagk

First I installed bsmn-pipeline under /home/$USER, which is on a 15 Gb filesystem on m5.large type AWS EC2.  This was too small for bsmn-pipeline (including resources).  I am installing it now under both /shared (40 Gb) and /efs (8 Eb).  If /shared is the recommended location it is not documented currently so I updated README.md with this info.

2019-01-16 22:15 UTC, kdaily requested changes
Thanks @attilagk other changes look good! Approve these suggestions and I'll get your changes merged in.

2019-01-16 22:15 UTC, kdaily commented on README.md
> +For installoing and setting up parallelcluster, please see the [`Getting Started Guide`](https://aws-parallelcluster.readthedocs.io/en/latest/getting_started.html) for AWS ParallelCluster.
```suggestion
For installing and setting up `parallelcluster`, please see the [`Getting Started Guide`](https://aws-parallelcluster.readthedocs.io/en/latest/getting_started.html) for AWS ParallelCluster.
```

2019-01-16 22:15 UTC, kdaily commented on README.md
> +Clone bsmn_pipeline where you want it installed in your cluster.  For example, if you work with an m5.large type AWS EC2 instance we recommend the file systems mounted at `/shared` or `/efs`.
```suggestion
Clone this repository where you want it installed in your cluster:

```
https://github.com/bsmn/bsmn-pipeline.git
```

If you work with an m5.large type AWS EC2 instance we recommend the file systems mounted at `/shared` or `/efs`.
```

2019-04-30 22:14 UTC, bintriz approved these changes

2019-04-30 22:14 UTC, bintriz approved these changes

2019-04-30 22:29 UTC, kdaily commented on README.md
> +For installoing and setting up parallelcluster, please see the [`Getting Started Guide`](https://aws-parallelcluster.readthedocs.io/en/latest/getting_started.html) for AWS ParallelCluster.
Hi @attilagk can you approve this suggestion?

2019-04-30 22:29 UTC, kdaily commented on README.md
> +Clone bsmn_pipeline where you want it installed in your cluster.  For example, if you work with an m5.large type AWS EC2 instance we recommend the file systems mounted at `/shared` or `/efs`.
Hi @attilagk can you approve this suggestion?

2019-06-18 15:23 UTC, merged